services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - ./csv_data:/csv_data
      - ./postgres-init/:/docker-entrypoint-initdb.d/

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "4334:8080"

volumes:
  postgres_data:
  minio_data:
