version: 2

models:
  - name: stg_products
    description: 'products table'
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_name
        tests:
          - not_null
          - unique
      - name: price
        tests:
          - not_null
      - name: category
        tests:
          - not_null