services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecomdata_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./csv_data:/csv_data

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "4334:8080"

volumes:
  postgres_data:
  minio_data:
