ecomm_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: ecomm_db
      schema: public
      threads: 1